### ISSUE TITLE
Using 2.0.11 ShowPad has no effect

### ISSUE THREAD

**Issue by ianhawki** [ljmerza/harmony-remote-card#12]
using latest homeassistant OS with latest harmony-remote-card and can not get showpad function to do anything... tried show_pad as well. tried in devices, activities and hub setting sections of code.

also centerpad i need to change to SELECT for apple TV

any ideas what i and doing wrong

sample code

```
type: custom:harmony-remote-card
entity: remote.cinema_hub
show_pad: false
activityEntity: select.cinema_hub_activities
activities:
  - activity: Apple TV on TV
    icon: mdi:apple
    name: On TV
    hide_icon: true
devices:
  - name: Apple TV
    commands:
      - Select
      - Mute
      - Home
      - name: Power Off
        command: PowerOff
```
