### ISSUE TITLE
Since update 1.7.1 issues with showpad

### ISSUE THREAD

**Issue by ianhawki** [ljmerza/harmony-remote-card#9]
in 1.7.0 ShowPad function doesn't work when you toggle true/false. However with version 1.7.1 the Pad disappears totally, the ShowPad function makes no different, have reverted to 1.7.0 for now.

also the Pad centre button doesn't seem to do anything.

**Comment by esackbauer** [comment]
Same here. No Pad anymore.

**Comment by ljmerza** [comment]
fixed in 1.7.3 make sure to set showPad: true

**Comment by alexdelprete** [comment]
> fixed in 1.7.3 make sure to set showPad: true

Not working for me. Reverted to 1.7.0 again.

With version 1.7.1 both pad and commands are not displayed.
With version 1.7.2 the card does not work at all (HA errors).
With version 1.7.3 pad is not available but commands are.

**Comment by ljmerza** [comment]
you set ` showPad: true` on v1.7.3?

**Comment by alexdelprete** [comment]
> you set ` showPad: true` on v1.7.3?

yes, it's always been there and didn't touch it when upgrading to >1.7.0 versions:

```
type: custom:harmony-remote-card
entity: remote.harmony_living
showPad: true
centerPad: Select
devices:
  - name: Samsung TV
    commands:
      - Exit
      - Mute
      - name: Vol+
        command: VolumeUp
      - name: Vol-
        command: VolumeDown
      - Pause
      - name: Chan-<
        command: ChannelPrev
      - name: Chan+
        command: ChannelUp
      - name: Chan-
        command: ChannelDown
```
